# Generated by Django 6.0.2 on 2026-02-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.CharField(default='default.png', max_length=200),
        ),
    ]
